# Generated by Django 3.1.1 on 2020-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20201106_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='justification',
            field=models.TextField(),
        ),
    ]
